export const fonts = {
  Courgette_Regular: require("../assets/fonts/Courgette-Regular.otf"),
  Roboto_Regular: require("../assets/fonts/Roboto-Regular.otf"),
  Roboto_Black: require("../assets/fonts/Roboto-Black.otf"),
  Roboto_BlackItalic: require("../assets/fonts/Roboto-BlackItalic.otf"),
  Roboto_Bold: require("../assets/fonts/Roboto-Bold.otf"),
  Roboto_Light: require("../assets/fonts/Roboto-Light.otf"),
  Roboto_Medium: require("../assets/fonts/Roboto-Medium.otf"),
  Roboto_Thin: require("../assets/fonts/Roboto-Thin.otf"),
  Roboto_Italic: require("../assets/fonts/Roboto-Italic.otf"),
  Roboto_BoldItalic: require("../assets/fonts/Roboto-BoldItalic.otf"),
  Roboto_LightItalic: require("../assets/fonts/Roboto-LightItalic.otf"),
  Roboto_MediumItalic: require("../assets/fonts/Roboto-MediumItalic.otf"),
  Roboto_ThinItalic: require("../assets/fonts/Roboto-ThinItalic.otf"),
};
